// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAPI.Models;

namespace TravelAPI.Migrations
{
    [DbContext(typeof(TravelAPIContext))]
    [Migration("20200330204507_reviewRatingToString")]
    partial class reviewRatingToString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelAPI.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("Rating");

                    b.HasKey("DestinationId");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "New York City",
                            Country = "United States",
                            Rating = 0
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "London",
                            Country = "England",
                            Rating = 0
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Toronto",
                            Country = "Canada",
                            Rating = 0
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Guangzho",
                            Country = "China",
                            Rating = 0
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Belfast",
                            Country = "Northern Ireland",
                            Rating = 0
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinationId");

                    b.Property<string>("Rating");

                    b.Property<string>("ReviewText");

                    b.Property<string>("user_name");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            DestinationId = 1,
                            Rating = "7",
                            ReviewText = "United States",
                            user_name = "New York"
                        },
                        new
                        {
                            ReviewId = 2,
                            DestinationId = 2,
                            Rating = "10",
                            ReviewText = "England",
                            user_name = "London"
                        },
                        new
                        {
                            ReviewId = 3,
                            DestinationId = 3,
                            Rating = "2",
                            ReviewText = "Canada",
                            user_name = "Toronto"
                        },
                        new
                        {
                            ReviewId = 4,
                            DestinationId = 4,
                            Rating = "4",
                            ReviewText = "China",
                            user_name = "Guangzho"
                        },
                        new
                        {
                            ReviewId = 5,
                            DestinationId = 5,
                            Rating = "10",
                            ReviewText = "Northern Ireland",
                            user_name = "Belfast"
                        });
                });

            modelBuilder.Entity("TravelAPI.Models.Review", b =>
                {
                    b.HasOne("TravelAPI.Models.Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
